"""This is the mapping after elasticsearch loaded all events."""

{'event': {'properties': {u'app': {'type': 'string'},
   u'created_at': {u'format': u'strict_date_optional_time||epoch_millis',
    'type': 'date'},
   u'creator': {'type': 'string'},
   u'data': {u'properties': {u'accepted_by': {'type': 'string'},
     u'accepted_by_first_name': {'type': 'string'},
     u'accepted_by_last_name': {'type': 'string'},
     u'agreed_to_terms': {'type': 'boolean'},
     u'app': {'type': 'string'},
     u'bio': {'type': 'string'},
     u'body': {'type': 'string'},
     u'browser': {u'properties': {u'name': {'type': 'string'},
       u'version': {'type': 'string'}},
      'type': 'object'},
     u'build': {'type': 'string'},
     u'class_id': {'type': 'string'},
     u'code': {'type': 'string'},
     u'course_id': {'type': 'string'},
     u'creator': {'type': 'string'},
     u'description': {'type': 'string'},
     u'device': {u'properties': {u'available': {'type': 'boolean'},
       u'cordova': {'type': 'string'},
       u'manufacturer': {'type': 'string'},
       u'model': {'type': 'string'},
       u'platform': {'type': 'string'},
       u'uuid': {'type': 'string'},
       u'version': {'type': 'string'}},
      'type': 'object'},
     u'email': {'type': 'string'},
     u'email_buddy_request': {'type': 'string'},
     u'email_classes': {'type': 'string'},
     u'email_my_groups': {'type': 'string'},
     u'email_private_message': {'type': 'string'},
     u'end': {'type': 'long'},
     u'end_hour': {'type': 'string'},
     u'error_message': {'type': 'string'},
     u'event_data': {u'properties': {u'buid': {'type': 'string'},
       u'created_at': {'type': 'long'},
       u'creator': {'type': 'string'},
       u'data': {u'properties': {u'accepted_by': {'type': 'string'},
         u'accepted_by_first_name': {'type': 'string'},
         u'accepted_by_last_name': {'type': 'string'},
         u'bio': {'type': 'string'},
         u'body': {'type': 'string'},
         u'class_id': {'type': 'string'},
         u'code': {'type': 'string'},
         u'course_id': {'type': 'string'},
         u'creator': {'type': 'string'},
         u'end': {'type': 'long'},
         u'end_hour': {'type': 'string'},
         u'first_name': {'type': 'string'},
         u'group_id': {'type': 'string'},
         u'id': {'type': 'string'},
         u'last_name': {'type': 'string'},
         u'name': {'type': 'string'},
         u'requested_by': {'type': 'string'},
         u'requested_by_first_name': {'type': 'string'},
         u'requested_by_last_name': {'type': 'string'},
         u'school_id': {'type': 'string'},
         u'sender': {'type': 'string'},
         u'start': {'type': 'long'},
         u'start_hour': {'type': 'string'},
         u'subject': {'type': 'string'},
         u'subject_code': {'type': 'string'},
         u'subject_icon': {'type': 'string'},
         u'subject_name': {'type': 'string'},
         u'where': {'type': 'string'}},
        'type': 'object'},
       u'event_id': {'type': 'string'},
       u'first_name': {'type': 'string'},
       u'group': {u'properties': {u'attending': {u'properties': {u'-JsR2brAMCP_V0uYTpw4': {'type': 'boolean'},
           u'-JsTtsLvKAMf2pvi5Xko': {'type': 'boolean'},
           u'-JsTut3zM9ZF_kb2XQ4o': {'type': 'boolean'},
           u'-JsXeLWtZJ5W_VUI4xjx': {'type': 'boolean'},
           u'-JsXf6crcFrPSRm9JBjr': {'type': 'boolean'},
           u'-JugfA2Pha1XdBmtvk_4': {'type': 'boolean'},
           u'-JxBi8eWO_y6TCc6B5Aa': {'type': 'boolean'}},
          'type': 'object'},
         u'profile': {u'properties': {u'code': {'type': 'string'},
           u'creator': {'type': 'string'},
           u'end': {'type': 'long'},
           u'end_hour': {'type': 'string'},
           u'group_id': {'type': 'string'},
           u'school_id': {'type': 'string'},
           u'start': {'type': 'long'},
           u'start_hour': {'type': 'string'},
           u'subject': {'type': 'string'},
           u'subject_code': {'type': 'string'},
           u'subject_icon': {'type': 'string'},
           u'where': {'type': 'string'}},
          'type': 'object'}},
        'type': 'object'},
       u'group_id': {'type': 'string'},
       u'involved': {'type': 'string'},
       u'last_name': {'type': 'string'},
       u'order': {'type': 'long'},
       u'reminder_type': {'type': 'string'},
       u'type': {'type': 'string'},
       u'uid': {'type': 'string'}},
      'type': 'object'},
     u'event_id': {'type': 'string'},
     u'first_name': {'type': 'string'},
     u'group_id': {'type': 'string'},
     u'id': {'type': 'string'},
     u'last_name': {'type': 'string'},
     u'logInString': {'type': 'string'},
     u'name': {'type': 'string'},
     u'on': {'type': 'boolean'},
     u'params': {u'properties': {u'course': {'type': 'string'},
       u'group_id': {'type': 'string'},
       u'subject': {'type': 'string'},
       u'user_id': {'type': 'string'}},
      'type': 'object'},
     u'password': {'type': 'string'},
     u'platform': {'type': 'string'},
     u'profile': {u'properties': {u'code': {'type': 'string'},
       u'creator': {'type': 'string'},
       u'description': {'type': 'string'},
       u'end': {'type': 'long'},
       u'end_hour': {'type': 'long'},
       u'group_id': {'type': 'string'},
       u'profile': {u'properties': {u'code': {'type': 'string'},
         u'creator': {'type': 'string'},
         u'description': {'type': 'string'},
         u'end': {'type': 'long'},
         u'end_hour': {'type': 'long'},
         u'group_id': {'type': 'string'},
         u'profile': {u'properties': {u'code': {'type': 'string'},
           u'creator': {'type': 'string'},
           u'description': {'type': 'string'},
           u'end': {'type': 'long'},
           u'end_hour': {'type': 'long'},
           u'group_id': {'type': 'string'},
           u'profile': {u'properties': {u'code': {'type': 'string'},
             u'creator': {'type': 'string'},
             u'description': {'type': 'string'},
             u'end': {'type': 'long'},
             u'end_hour': {'type': 'long'},
             u'group_id': {'type': 'string'},
             u'school_id': {'type': 'string'},
             u'start': {'type': 'long'},
             u'start_hour': {'type': 'long'},
             u'subject': {'type': 'string'},
             u'subject_code': {'type': 'string'},
             u'subject_icon': {'type': 'string'},
             u'where': {'type': 'string'}},
            'type': 'object'},
           u'school_id': {'type': 'string'},
           u'start': {'type': 'long'},
           u'start_hour': {'type': 'long'},
           u'subject': {'type': 'string'},
           u'subject_code': {'type': 'string'},
           u'subject_icon': {'type': 'string'},
           u'where': {'type': 'string'}},
          'type': 'object'},
         u'school_id': {'type': 'string'},
         u'start': {'type': 'long'},
         u'start_hour': {'type': 'long'},
         u'subject': {'type': 'string'},
         u'subject_code': {'type': 'string'},
         u'subject_icon': {'type': 'string'},
         u'where': {'type': 'string'}},
        'type': 'object'},
       u'school_id': {'type': 'string'},
       u'start': {'type': 'long'},
       u'start_hour': {'type': 'long'},
       u'subject': {'type': 'string'},
       u'subject_code': {'type': 'string'},
       u'subject_icon': {'type': 'string'},
       u'where': {'type': 'string'}},
      'type': 'object'},
     u'push_buddy_request': {'type': 'string'},
     u'push_classes': {'type': 'string'},
     u'push_my_groups': {'type': 'string'},
     u'push_private_message': {'type': 'string'},
     u'recipient': {'type': 'string'},
     u'recipient_first_name': {'type': 'string'},
     u'recipient_last_name': {'type': 'string'},
     u'requested_by': {'type': 'string'},
     u'requested_by_first_name': {'type': 'string'},
     u'requested_by_last_name': {'type': 'string'},
     u'school_id': {'type': 'string'},
     u'section': {'type': 'string'},
     u'sender': {'type': 'string'},
     u'sender_first_name': {'type': 'string'},
     u'sender_last_name': {'type': 'string'},
     u'sent_at': {'type': 'long'},
     u'start': {'type': 'long'},
     u'start_hour': {'type': 'string'},
     u'state': {'type': 'string'},
     u'subject': {'type': 'string'},
     u'subject_code': {'type': 'string'},
     u'subject_icon': {'type': 'string'},
     u'subject_name': {'type': 'string'},
     u'target': {'type': 'string'},
     u'target_to': {'type': 'string'},
     u'target_to_first_name': {'type': 'string'},
     u'target_to_last_name': {'type': 'string'},
     u'thread_id': {'type': 'string'},
     u'type': {'type': 'string'},
     u'url': {'type': 'string'},
     u'where': {'type': 'string'}},
    'type': 'object'},
   u'first_name': {'type': 'string'},
   u'id': {'type': 'string'},
   u'involved': {'type': 'string'},
   u'last_name': {'type': 'string'},
   u'order': {'type': 'long'},
   u'profile_pic_url_tiny': {'type': 'string'},
   u'type': {'type': 'string'}}}}
